name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Analyze with SonarQube
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Use the Node.js version that fits your project needs

    - name: Install dependencies
      run: npm install

    - name: SonarQube Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: npx sonar-scanner \
        sonar-scanner \
               -Dsonar.projectKey=test \
               -Dsonar.sources=. \
               -Dsonar.host.url=http://34.221.130.56:9000 \
               -Dsonar.login=02550d7bd01a52d64877813d3f8b0a2f528a746c
