name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history for better SonarQube analysis

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust based on your project's requirements

      - name: Install dependencies
        run: npm install

      - name: Install SonarQube Scanner
        run: npm install -g sonarqube-scanner

      - name: Run SonarQube Scan
        run: |
          sonar-scanner \
          -Dsonar.projectKey=test1 \
          -Dsonar.sources=. \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Download SonarQube Report (JSON)
        run: |
          curl -u ${{ secrets.SONAR_TOKEN }}: \
          "http://ec2-35-161-255-33.us-west-2.compute.amazonaws.com:9000/api/issues/search?projectKey=test1" \
          -o sonarqube-report.json

      - name: Upload Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sonarqube-report
          path: sonarqube-report.json
